### ISSUE TITLE
Developer mailing-list is configured in Spanish

### ISSUE THREAD

**Issue by a3nm** [TheOnlineJudge/ojudge#106] opened 2020-04-23 10:45 UTC
Hi, the email confirmation when joining the developer mailing-list is in Spanish: "Felicidades, un moderador de grupo ha aprobado tu solicitud para unirte al grupo OJudge Developers."

Shouldn't it be configured in English?

**Comment by enjolras** [comment] 2020-04-23 11:05
I have checked that the Group is, indeed, configured in English, in the only setting that allows the admin to configure anything language related. I assume that your main overall config is in English and don't have any Spanish related setting in your setup. Closing, also, as this is not a bug related to the development code.

**Closed as completed by enjolras** 2020-04-23 11:05 UTC

**Comment by a3nm** [comment] 2020-04-23 11:34
No, I don't have any Spanish in my setup so I don't know where this could have come from. Sorry if this wasn't the right place to report it.

**Comment by enjolras** [comment] 2020-04-24 00:21
I will double check it. But the setting is set to American English in the only place any such option appears.

**Comment by a3nm** [comment] 2020-04-24 06:47
Nah, don't bother if it's just that one email. :) I'll complain again here if I see Spanish again.

**Comment by enjolras** [comment] 2020-04-24 07:55
> Nah, don't bother if it's just that one email. :) I'll complain again here if I see Spanish again.

And then I'll fix it the Spanish way (mañana) :laughing:  :laughing: :laughing: :laughing:
